return {
  {
    "romgrk/barbar.nvim",
    event = "VeryLazy", -- 起動完了後に遅延読み込み（1ファイル時は非表示なので影響なし）
    dependencies = {
      "lewis6991/gitsigns.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    init = function()
      vim.g.barbar_auto_setup = false
    end,
    opts = {
      animation = true,
      auto_hide = false,
      tabpages = true,
      closable = true,
      clickable = true,
      exclude_ft = { "javascript" },
      exclude_name = { "package.json" },
      focus_on_close = "left",
      hide = { extensions = true, inactive = false },
      highlight_alternate = false,
      highlight_inactive_file_icons = false,
      highlight_visible = true,
      icons = {
        buffer_index = false,
        buffer_number = false,
        button = "",
        diagnostics = {
          [vim.diagnostic.severity.ERROR] = { enabled = true, icon = "ﬀ" },
          [vim.diagnostic.severity.WARN] = { enabled = false },
          [vim.diagnostic.severity.INFO] = { enabled = false },
          [vim.diagnostic.severity.HINT] = { enabled = true },
        },
        gitsigns = {
          added = { enabled = true, icon = "+" },
          changed = { enabled = true, icon = "~" },
          deleted = { enabled = true, icon = "-" },
        },
        filetype = {
          custom_colors = false,
          enabled = true,
        },
        separator = { left = "▎", right = "" },
        separator_at_end = true,
        modified = { button = "●" },
        pinned = { button = "", filename = true },
        preset = "default",
        alternate = { filetype = { enabled = false } },
        current = { buffer_index = true },
        inactive = { button = "×" },
        visible = { modified = { buffer_number = false } },
      },
      insert_at_end = false,
      insert_at_start = false,
      maximum_padding = 1,
      minimum_padding = 1,
      maximum_length = 30,
      minimum_length = 0,
      semantic_letters = true,
      sidebar_filetypes = {
        NvimTree = true,
        undotree = {
          text = "undotree",
          align = "center",
        },
        ["neo-tree"] = { event = "BufWipeout" },
        Outline = { event = "BufWinLeave", text = "symbols-outline", align = "right" },
      },
      sort = {
        ignore_case = false,
      },
    },
    keys = {
      { "<A-,>", "<Cmd>BufferPrevious<CR>", desc = "Previous buffer" },
      { "<A-.>", "<Cmd>BufferNext<CR>", desc = "Next buffer" },
      { "<A-<>", "<Cmd>BufferMovePrevious<CR>", desc = "Move buffer left" },
      { "<A->>", "<Cmd>BufferMoveNext<CR>", desc = "Move buffer right" },
      { "<A-1>", "<Cmd>BufferGoto 1<CR>", desc = "Go to buffer 1" },
      { "<A-2>", "<Cmd>BufferGoto 2<CR>", desc = "Go to buffer 2" },
      { "<A-3>", "<Cmd>BufferGoto 3<CR>", desc = "Go to buffer 3" },
      { "<A-4>", "<Cmd>BufferGoto 4<CR>", desc = "Go to buffer 4" },
      { "<A-5>", "<Cmd>BufferGoto 5<CR>", desc = "Go to buffer 5" },
      { "<A-6>", "<Cmd>BufferGoto 6<CR>", desc = "Go to buffer 6" },
      { "<A-7>", "<Cmd>BufferGoto 7<CR>", desc = "Go to buffer 7" },
      { "<A-8>", "<Cmd>BufferGoto 8<CR>", desc = "Go to buffer 8" },
      { "<A-9>", "<Cmd>BufferGoto 9<CR>", desc = "Go to buffer 9" },
      { "<A-0>", "<Cmd>BufferLast<CR>", desc = "Go to last buffer" },
      { "<A-p>", "<Cmd>BufferPin<CR>", desc = "Pin/unpin buffer" },
      { "<A-c>", "<Cmd>BufferClose<CR>", desc = "Close buffer" },
      { "<C-p>", "<Cmd>BufferPick<CR>", desc = "Pick buffer" },
      { "<A-s-c>", "<Cmd>BufferCloseAllButCurrent<CR>", desc = "Close all but current" },
      { "<leader>bb", "<Cmd>BufferOrderByBufferNumber<CR>", desc = "Order by buffer number" },
      { "<leader>bd", "<Cmd>BufferOrderByDirectory<CR>", desc = "Order by directory" },
      { "<leader>bl", "<Cmd>BufferOrderByLanguage<CR>", desc = "Order by language" },
      { "<leader>bw", "<Cmd>BufferOrderByWindowNumber<CR>", desc = "Order by window number" },
    },
  },
}